List<String> wordEnglish = [
  'Extraordinary',
  'Dispatcher',
  'Decade',
  'Fragile',
  'Dilemma',
  'Reinforce',
  'Prophet',
  'Inspire',
  'Coincidence',
  'Controversial',
  'Farewell',
  'Mutual',
  'Plagiarism',
  'Congratulations',
  'Schedule',
  'Counterfeit',
  'Penalty',
  'Distracted',
  'Example,Instance',
  'Remind',
  'Reminder',
  'Compliment',
  'Chores',
  'Prodigy',
  'Scar',
  'Climate',
  'Whisper',
  'Precaution',
  'Syllabus',
  'Architect',
  'Promise',
  'Since',
  'Awareness',
  'Sibling',
  'Survive',
  'Rescue',
  'Inevitable',
  'Reduce',
  'Brotherhood',
  'Anniversary',
  'Fasting',
  'Addict',
  'Addiction',
  'Computer engineering, Software engineering',
  'Pandemic',
  'Skin',
  'Prayer rug - Prayer mat',
  'Bald',
  'Ignorance',
  'Relief',
  'Failure',
];
List<String> wordTurkish = [
  'Olağandışı, Görülmemiş, Alışılmamış',
  'Hareket Memuru, Sevk Memuru',
  '10 yıl',
  'Hassas, Kırılgan',
  'İkilem, Çıkmaz, Açmaz',
  'Güçlendirmek, Sağlamlaştırmak, Takviye etmek',
  'Peygamber',
  'İlham Vermek',
  'Rastlantı, Tesadüf',
  'Anlaşmazlığa neden olan, Tartışmaya yol açan',
  'Elveda, Uğurlama',
  'Karşılıklı, Ortak',
  'İntihal, Emek Hırsızlığı, Eser Hırsızlığı',
  'Tebrikler, Kutlarız, Tebrik Ederiz',
  'Program, Plan, Takvim Belirlemek',
  'Sahte',
  'Ceza, Penaltı(Futbol)',
  'Dikkati Dağılmış',
  'Örnek, Misal',
  'Hatırlatmak',
  'Hatırlarıcı',
  'İltifat, Övgü',
  'Ev İşleri',
  'Dahi, Olağanüstü  şey',
  'Yara izi',
  'İklim',
  'Fısıldamak, Fısıltı',
  'Önlem, Tedbir',
  'Müfredat',
  'Mimar',
  'Söz vermek, Söz',
  '-den beri',
  'Farkındalık',
  'Kardeş',
  'Yaşamayı sürdürmek, Hayatta kalmak',
  'Kurtarmak, Hayat Kurtarmak, (Hacizden Kurtarmak)',
  'Kaçınılmaz',
  'Azaltmak',
  'Kardeşlik',
  'Yıl dönümü',
  'Oruç tutmak',
  'Bağımlı olmak',
  'Bağımlılık',
  'Bilgisayar mühendisliği, Yazılım mühendisliği',
  'Pandemi, Salgın',
  'Deri',
  'Seccade',
  'Kel',
  'Cahillik, Cehalet, Bilgisizlik',
  'Rahatlama',
  'Başarısızlık',
];
List<String> wordMeaning = [
'Bu kelime pozitif anlamlarda kullanılıyor genelde. Mesela, bit futbolcu sıradışı bir gol attığı zaman(Örneğin; Röveşatayla) bu kelimeyi kullanabiliriz veya bu sıfatı hakeden bazı insanlar içinde bu kelime kullanılabilir',
'İnsaları yada acil durum araçlarını ihtiyacı olan yerlere göndermekle sorumlu/yükümlü kişi. Acil durum araçlarını itfaiye aracı yada ambulans gibi düşünebiliriz.Kısaca, dispatcher dediğimiz kelime bir kişi için kullanılır, bu kişi de sen 110,112,155 aradığında karşına çıkan kişidir. Ama bunun en iyi örneği bu Amerikalılarda olan 911 dir orası sadece polis yada ambulans değil hepsini kapsıyor. Kelimenin türkçe karşılığı kulağa garip gelebilir ama her kelimenin birebir türkçesini öğrenmek zorunda değiliz. Kelimenin anlmını bilip, kullanabiliyorsak bize yeterli diye düşünüyorum ama direkt çeviri için hareket/sevk memuru diyebiliriz.',
'Bu kelimeyi daha çok ileride yazacağınız "Essay" dediğimiz yazılarda yazınızın bir tık daha üst düzey durması için kullanacaksınız. Last 10 years yazmak yerine last decade yazmak kelime bilginizin daha iyi olduğunu gösterebilir. Not: Essay- rapor,makale demek. Üniversitelerin hazırlık sınıflarında bolca yazdırılır.',
'Bu kelimeyi daha çok kargo kutularında görebilirsiniz, Taşınacak olan kargonun hassas veya kırılgan olabileceğini ifade eder.',
'Bazen seçim yapmakta zorlandığımız durumlar olur. Öyle durumlar için bu kelimeyi kullanabiliriz. Genelde iki durum arasında kalma durumlarında kullanılır ama 2\'den fazla seçenek olursa bile kelime hala kullanılabilir.  Bazı ünlü"dilemma"lar vardır bunlardan bazıları direkt olarak seçim yapmakla ilgili değil ama izlemesi, öğrenmesi benim hoşuma giden şeyler. Aşağıdan izleyebilirsiniz.',
'Çevirisinden de anlaşılacağı üzere bir şeylerin sağlamlığının arttırılmasıyla iligli konuşulurken bu kelimeyi kullanabiliriz.',
'ALLAH(c.c.) tarafından bir dini veya dinî öğretiyi yaymakla görevlendirilen kişi. ',
'İnsanlara olumlu duygular hissettirme durumu diyebiliriz sanırsam. Bunun en güzel örneklerinden birisi Mertin Luther King\'in siyahi haklarıyla ilgili konuşmasıdır. Aşağıdan izleyebilirsiniz.',
'Bu kelime türkçe anlamından da anlaşılacağı üzere trsadüf eseri gelişen olaylar için kullanılıyor.',
'Bu kelime bir sıfattır. Yakışıklı, genç vb gibi. Bu kelimeyi tartışmalı konularla ilgili yazılarda görmeniz olasıdır. Örneğin, Son 10 yılda(Decade), Küresel ısınma insanlık için tartışmaya yol açan(Controversial) bir konu haline gelmiştir.',
'Uzun bir süre görüşmeyeceğiniz biriyle ayrılırken söylenebilcek bir kelime. Bir diğer anlamı ise, Ayrılacak veya emekli olacak birisini onurlandırmak amacıyla yapılan resmi bir olay veya parti. Aşağıdaysa ünlü futbolcular için düzenlenen farewellardan kısa bir kesit izleyebilirsiniz.',
'Eğer Facebooku ingilizce kullanıyorsanız bunu sıkça görürsünüz. Arkadaş listenizde olmayan birini eklemeye çalışırken eğer ortak arkadaşınız varsa Mutual friends diyerek gösterir size. İlk anlamına gelirsek yani "Karşılıklı" ya. İki insanın birbiri için duygularının aynı olması örneğin iki arkadaşın birbirini dost olarak görmesi.',
'Bu kelime akademik hayatta yapılmaması gereken şeylerin başında gelir. Bu başkasının bir eserini ona doğru şekilde atıf vermeden kullanmak demektir. Akademik yazılarda bunu yapamk bir suçtur. Eğer bir akademik yazı yazmanız gerekirse,  atıf ve kaynakça kullanımı iyice araştırmanız lazım.',
'Bu kelime okunuşu ile ülkemizde olay olmuştur. O yüzden okunuşunu çok iyi bilmemiz gerekiyor 😜. Bu kelimeyi doğal olarak birini tebrik etmek istediğiniz zaman kullanıyorsunuz.',
'Bu kelime hem isim hem fiil olarak kullanılabilir. İsim olarak anlamı şudur; Yapmayı planladığımız veya meydana geleceği zaman belli olan şeyleri gösteren program. Aşağıda resimler kısmından da nasıl bir şeyi anlatmak istediğimi görebilirsiniz. Fiil olarak ise Bir şeyi belirli bir zamanda meydana gelmesi için planlamak.',
'Bir şeyin orijinaline benzemesi amacıyla yapılmış olan şey. Bu kelime pek sık çıkmaz karşınıza çünkü daha yaygını olan "fake" kelimesi var. Bu kelimenin özelliği ise böyle özel eşyalar vardır ya Koleksiyonluk eşyalar, fiyat bakımından çok değerli olan eşyalardan bahsediyorum. Bu eşyaların sahteleri için Counterfeit kelimesi kullanılabilir. Örneğin,  çok değerli bir eşya var elinizde ve bunun sahte olup olmadığını anlayabilecek bilgiye sahip olan birine gösteriyorsunuz. Eğer ürününüz sahteyse, size "Bu ürün counterfeit(sahte) denecektir muhtemelen.',
'Bugünki kelimemizi çoğumuz önceden de biliyoruzdur muhtemelen. Ama benim bahsetmek istediğim anlamı "Ceza" olan anlamı. Eğer bir kutala uymazsanız veya bir anlaşmayı çiğnerseniz başınıza gelecek muhtemelen para ödemesi içeren ceza türü. Bildiğimiz penaltı anlamı ise zaten hayatımızda sıkça görüyoruz. Tahminimce futbola penaltı kuralı ilk geldiği zaman ceza sahası içindeki faullere bir ceza vermek için bu kelime kullanıldı.',
'Hayatımız dikkatimizi dağıtan etkenlerle dolu. Araba kullanırken telefonla uğraşmak verilebilecek en iyi örneklerden biri sanırsam. İşte biz bu duruma, yani dikkatimiz dağıldıktan sonraki duruma Distracted yani dikkati dağılmış diyoruz. Burdan ufak bir kamu spotu verelim, 2017 yılında yayınlanmış bir haberde okuduğuma göre trafik kazalarının yüzde 60\'ı cep telefonu kullanımından kaynaklanıyormuş. Lütfen sürüşlerimizi daha güvenli yapalım.',
'Bu kelimeleri açıklama yaptıktan sonra örnek vermek istediğiniz zaman şu kalıplarla " For Example veya For instance" diyerek örneklerimizi verebiliriz.',
'Birine unuttuğu veya unutma ihtimali olan bir şeyi düşünmesini sağlamak. Ben de size bir şey hatırlatayım, Kelimeleri günü gününe öğrenmeyi uuntmayın lütfen :D.',
'Birine bir şeyi yapmasını gerektiğini hatırlatan yazılı veya sözlü mesaj. Önceki gün remind kelimesi karşınızı çıkmıştı bugün ise reminder :D. Bazı kelimelere ufak ekler gelince yeni kelimeler ortaya çıkabiliyor. Bu örnekte olduğu üzere -er ekiyle yeni bir kelime ortaya çıkmış. Yani, aslında böyle ufak taktiklerle keilme haznemizi daha da geliştirebiliriz.',
'Direkt örnek vererek açıklamak benim için daha kolay olacak sanırsam. Örneğin, "Sen harika bir arkadaşsın". Bu bir complimenttir mesela. ',
'Aslında Chore zevksiz iş demekmiş, Chores(-s var bunun sonunda) ise direk ev işleri için kullanılıyor. Bildiğimiz üzere ev işleri genelde zevksiz olduğu için böyle bir kullanım tercih etmiş olabilirler. Yine ufak bir kamu spotu geçeyim. Ev işlerinde lütfen tüm yükü tek bir kişiye yüklemeyelim, birbirimize yardım etmeye çalışalım. Kamu spotumuzda bittiğine göre aşağıdaki resimlerde hem ingilizce hem türkçe şekilde bazı ev işlerini bulabilirsiniz.',
'Olağanüstü yetenekleri olan kişilere için kullanılan bir sıfattır. Bu yetenek genelde kendisini çocuk yaşta gösterir. O yüzden "child proidgy" yani "Dahi çocuk", "Harika çocuk" gibi kullanımları görebilirsiniz. Aşağıda bazı dahi çocuklarla ilgili bilgiler bulablirsiniz.',
'Genelde vücutta görülebilen kesik vb gibi durumlar sonucu oluşmuş işaretler diyebiliriz. Fiziksel olması şart değil Psikoloji hasarlar için de kullanılabilir. Ama genelde deri üzerindeki hasarlarda kullanmak daha mantıklı sanırsam. ',
'Bu kelimeyi "Climate Change" ile beraber görmeniz çok olası. İklim değişikliği anlamına geliyor. Climate Change konusuda Essaylerin çok popüler konularından biridir. Bu kelimenin okunuşuna lütfen dikkat edelim, çünkü okunuşu kılimeyt değil, "kılaymıt"\'tır. Zaten sesli olarak dinlerseniz çok daha iyi öğrenirsiniz.',
'Çok sessizce konuşmak için kullanılan bir kelimedir. Hem isim hem fiil olarak kullanılabilir. ',
'Tehlikeli şeyler önlemek için yapılan eylemler bütünü. Ben bu yazıları yazarken Covid-19 hala bizim önemli bir tehditti ve Yaşadığım yerde de bununla ilgili bir sürü önlemler alınmıştı. Aşağıda Covid-19 için bazı önlemler bırakıyorum. Umarım, siz bunları okurken hayırlısıyla pandemi dönemini bitirmiş oluruz.',
'İlgili derste işlencek konular bütününe müfredat denir.',
'Binaları tasarlayan ve doğru inşa edildiklerinden emin olan kişi. Matrix filmlerinde de ünlü bir mimar vardı sanırsam. Matrixe hakin olanlar bu kelimeyi ordan hatırlayabilirler :D.',
'Hayatta söz verme olayına çok dikkat etmemiz lazım. Eğer bir söz verdiysek, o sözü tutmamız lazım(Verdiğimiz söz bizim veya herhangi biri veya insanlık için zararlıysa tutmamak daha mantıklı sanırsam).',
'Bu kelimeyi tabelalarda görmüş olmanız çok muhtemel. Örneğin, bir restoran 2000 yılından beri faaliyet gösteriyorsa tabelasına "since 2000" yazabilir. Eğer cümle iligili anlamı taşıyorsa, bu kelimeyi sadece tabelalarda değil, her yerde kullanabiliriz. Mesela, Yaz tatilini ocak ayından beri bekliyor(Since January).',
'Bir olay hakkında bilgi sahibi olmak diyebiliriz. Kamu spotu : Etrafımızda bir sürü olay oluyor ve hiçbirinin farkında değiliz. İnsanlar açlıktan veya gereken tedaviyi alamadıklar için veya buna benzer başka sebeplerden ölüyorlar. Biz ise etrafımızda bunlar olurken hala günlük hayatımıza devam ediyoruz. Lütfen bazı şeylerin farkına varıp, bunları değiştirmeye çalışalım. Sakın gücünüzün yetmeyeceğini düşünmeyin, siz elinizden geleni yapın.',
'Normalde brother ve sister kelimeleri var erkek kardeş ve kız kardeş için. Ama sibling ise "Kaç kardeşiniz var(cinsiyet belirtmiyoruz)" sorusundaki kardeş kelimesine denk geliyor. Mesela Benim 2 kardeşim var, bir erkek ve bir kız. Eskiden aklıma gelirdi ingilizcede kardeş kelimesi kendi başına yok mu diye. Meğersem varmış :D.',
'Eğer Türkiyede yaşıyorsanız zaten bu kelimeyi yaklaşık son 10 - 15 yıldır Acun Ilıcalı sayesinde görmüşsünüzdür. Bilmeyenler için ufak bir özet geçiyim, Acun Ilıcalının düzenlediği "Survivor" adlı bir yarışma var. Bu yarışmada yaklaşık 20-40 kişi bir adaya bırakılıyor ve orda hayatlarına devam etmeleri isteniyor. Ödül oyunları ve yarışmacı eleme gibi sistemler var Survivor yarışmasında. Bu kadar Survivor yeter. Bu arada anlam olaraksa Survivor - Hayatta Kalan, kalmaya çalışan olarak düşünebiliriz.',
'Birisini tehlikeli bir durumdan kurtarmak. Örneğin, Askerlerimizin yaptıkları kurtarma operasyonları buna örnek verilebilir. Burdan tüm askerlerimize selam olsun.',
'Eğer marvel hayranıysanız zaten bu kelimeyi duymuşsunuzdur. Spoiler uyarısı : Thanos bu kelimeyi sonsuzluk taşları eldivene takılı haldeyken "I am inevitable" yani "ben kaçınılmazım" diyerek tüm canlıların yarısını yok etmişti. Aşağıda Thanosun farklı dillerdeki Ben Kaçınılmazım diyişini izleyebilirsiniz. ',
'Önem,derece,miktar bakımından bir şeyi daha küçük hale getirmek. Bu kelimeyi League of Legends oyanyanlar muhtemelen çokça duymuştur. Oyunda "Cooldown Reduction" yani Bekleme süresinde azalma olarak geçiyor. Bu sayede yeteneklerinizi daha sık bir şekilde atabiliyorsunuz.',
'Belirli bir organizasyonun üyelerine denebilir. Üyeler aynı amacı paylaşıyor ve destekliyorsa buna da kardeşlik denebilir.',
'Bu kelimeyi Evlilik yıl dönümünden kolaylıkla hatırlayabilirsiniz. Wedding Anniversary(Evlilik Yıl dönümü).',
'Belirli bir süre boyunca yemek yememe veya içecek içmeme eylemi(Yani vücuda besin almama durumu). Benimde dinim olan İslam dinindeki Oruç da buna bir örnektir.Kullanım olarak "Fast" hem "Oruç" hem "Oruç Tutmak" olarak kullanılabilir. Fasting olarak yazmamım sebebi fast kelimesinin ayrıca "hızlı" anlamına da gelmesi(-ing takısının şimdiki zamandaki kullanımdan başka bir özelliği ise fiilere eklendiğinde onları isim yapmasıdır. Ama şuan konumuz bu değil. Daha detaylı bilgi için internette araştırabilirsiniz.) Aşağıya orucun faydalarıyla ilgili kaynaklar burakıyorum, incelerseniz çok şey kazaacağınızı düşünüyorum.',
'Bir şeyi özellikle bize zarar veren bir şeyi yapmaktan kendimizi alıkoyama eylemi. Bağımlı olmaktan kurtulmanın bana göre en iyi çözümlerinden biri hiç başlamamaktır. Lütfen herhangi bir kötü alışkanlığa başlamayın.',
'Evet, bir önceki kelimenin isim hali. Bağımlılıklara örnek olarak, sigara, alkol veya uyuşturucu bağımlılığı verilebilir. 115 Yeşilay, 191 Uyuşturucu ile Mücadele Danışma ve Destek Hattı gibi hatlar bağımlılıkla mücadeleye karşı Türkiyede hizmet veren hatlardır.',
'"Engineer" kelimesi "Mühendis" anlamına gelmektedir. "Computer" ise "Bilgisayar", "Software" ise "Yazılım". Ekstra bilgi olarak "Hardware" ise "Donanım" demektir. Bu arada bu uygulamayı yaptığım sırada bende bir bilgisayar mühendisliği öğrencisyim :D. ',
'Sanırsam hepimiz zaten bu kelimeyi Covid-19 sayesinde biliyoruz. Ama yinede açıklamak gerekirse, Bir hastalığın çok geniş alanlara(Dünya Çapı, Kıtasal boyut gibi)yayılması. Bu kelimenin bir de küçük kardeşi var. O ise "Epidemic". Epidemic ise daha pandemic\'e göre daha küçük alanda yayılması durumunda kullanılan isim. Örneğin, Koronavirüs hastalığı ilk çıktığında bir epidemic\'ti sonradan dünya geneline yayıldığında pandemic olarak ilan edildi.',
'İnsan,hayvan,meyve ve sebze gibi varlıkların dış katmanında bulunan tabakaya verilen ad diyebiliriz. Kamu Spotu: Derideki renk farklılığı yüzüzünden yapılan ayırımlara yani Irkçılığa hayır. Peygamber Efendimiz (s.a.s) buyuruyor ki “Ey insanlar! Dikkat ediniz; Rabbiniz birdir, atanız da birdir. Takva dışında Arap’ın Arap olmayana, Arap olmayanın Arap’a; beyazın siyaha, Siyahın beyaza bir üstünlüğü yoktur. Üstünlük ancak takvadadır. ”.',
'Müslümanların namazlarını kılmak için yere serdiği eşya diyebiliriz. ',
'Kafada az veya hiç saç olmaması durumu. Örnek olarak Alex de souza veya ajan 47(Hitman) verilebilir.',
'Bilgi eksikliği diyebiliriz.',
'Bize kötü hissettiren bir durumun etkisnin üzerimizden kalktığı anda hissedilen duygu,his.',
'Nasa\'da şöyle bir söz vardır "Failure is not an option" yani "Başarısızlık bir seçenek değil" veya "Başarısızlık kabul edilemez" anlamına gelmektedir.'
];